export const dummydata = [
  {
    image: require("./assets/images/devlinks.webp"),
    projectTitle: "A Developer Link Management Platform -for Toyan",
    projectCategory: "ReactJS, Typescript",
    desc: "DevLinks is a web app for managing and sharing links easily. It offers link CRUD, drag-and-drop, real-time previews, and profile setup with pictures.",
    link: "https://toyan-devlinks.vercel.app/",
    // githubLink: "https://github.com/Olatoyan/link-sharing-app",
  },
  {
    image: require("./assets/images/assure.webp"),
    projectTitle: "Assure Website -for Assure",
    projectCategory: "NextJS, Typescript",
    desc: "Assure is a virtual care delivery to empower both patients and clinicians.",
    link: "https://forassure.com/",
    // githubLink: "https://github.com/Olatoyan/link-sharing-app",
  },
  {
    image: require("./assets/images/connect-four.webp"),
    projectTitle:
      "An Interactive Online Game with AI, Multiplayer & Spectating",
    projectCategory: "NextJS, Typescript, ExpressJS, TailwindCSS",
    desc: "Connect Four is a classic strategy game reimagined for the web. Challenge friends or our competitive AI, spectate live matches, and celebrate wins with unlockable achievements. Enjoy quick chat, real-time reactions, live voice chat, and smooth animations for an engaging multiplayer experience.",
    link: "https://toyan-connect-four.vercel.app/",
    // githubLink: "https://github.com/Olatoyan/link-sharing-app",
  },
  {
    image: require("./assets/images/jikoo.webp"),
    projectTitle: "Jikoo Website",
    projectCategory: "NextJS, Typescript, TailwindCSS",
    desc: "Jikoo connects you to the finest restaurants, delivering delicious meals to your doorstep with ease.",
    link: "https://jikoo-landing-page.vercel.app/",
    // githubLink: "https://github.com/Olatoyan/link-sharing-app",
  },
  {
    image: require("./assets/images/sabi.png"),
    projectTitle: "Sabiplex",
    projectCategory: "NextJS, Clerk",
    link: "https://sabiplexapp.vercel.app/",
    githubLink: "https://github.com/Manuelthegoat/sabiplex-next",
  },
  {
    image: require("./assets/images/iden.png"),
    projectTitle: "Identifii",
    projectCategory: "Solidity, NextJS, Prima",
    link: "https://oppblockidentifii.vercel.app/",
    githubLink: "https://github.com/Manuelthegoat/IdentiFii-Blockathon",
  },

  {
    image: require("./assets/images/project-5.png"),
    projectTitle: "Salinaka Eyecare",
    projectCategory: "Fullstack Ecommerce (react)",
    link: "https://salinaka-ecommerce.web.app/",
  },
  {
    image: require("./assets/images/project-6.png"),
    projectTitle: "Commerce js",
    projectCategory: "Fullstack Ecommerce (react)",
    link: "https://commerce-js.netlify.app/",
  },
  {
    image: require("./assets/images/project-2.png"),
    projectTitle: "My Former Portfolio",
    projectCategory: "Portfolio | Frontend (react)",
    link: "https://uwadiegwu.vercel.app/",
  },
  {
    image: require("./assets/images/project-3.png"),
    projectTitle: "SparkMovies",
    projectCategory: "Movie Website (react API project)",
    link: "https://sparkmedia.vercel.app/",
  },
  {
    image: require("./assets/images/project-4.png"),
    projectTitle: "Janicenter Africa",
    projectCategory: "Frontend (react)",
    link: "https://janicenter.org/",
  },
  {
    image: require("./assets/images/project-7.png"),
    projectTitle: "E&R Global Resources",
    projectCategory: "Frontend (react)",
    link: "https://erglobalresources.com/",
  },
  {
    image: require("./assets/images/project-8.png"),
    projectTitle: "Afor Mart",
    projectCategory: "Ecommerce (react)",
    link: "https://aformart.vercel.app/products/",
  },
  {
    image: require("./assets/images/project-9.png"),
    projectTitle: "Codefunky",
    projectCategory: "Portfolio | Frontend (react)",
    link: "https://codefunky.vercel.app/",
  },
];
